config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :chintus
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
#get 'hello', to:'application#hello'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#about'
  get 'about',to: 'pages#about'
  get 'sai',to: 'chintus#chintu'
  get 'home',to: 'pages#home'
  get 'signup',to: 'customers#new'
  resources :customers,except:[:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

end

app/models/chintu.rb
class Chintu < ApplicationRecord
    belongs_to :customer
    belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

end

app/models/customer.rb
class Customer < ApplicationRecord
<<<<<<< user-autentication
  before_save :downcase_email
  def downcase_email
    self.email = email.downcase
    self.email
=======
  before_save :downcase_email 
  def downcase_email
   self.email=email.downcase
   self.email
>>>>>>> local
  end
   has_many :chintus
  validates :username, presence: true,
                 uniqueness: { case_sensitive: false },
                 length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                 uniqueness: { case_sensitive: false },
                 length: { maximum: 105 },
                 format: { with: VALID_EMAIL_REGEX }
   has_secure_password
end

app/models/user.rb
class User < ApplicationRecord
  has_many :chintus
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_customer, :logged_in?

  def current_customer
    @current_customer ||= Customer.find(session[:customer_id]) if session[:customer_id]
  end

  def logged_in?
    !!current_customer
  end

  def require_customer
    unless logged_in?
      flash[:alert] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/chintus_controller.rb
class ChintusController < ApplicationController   
  
  before_action :set_chintu, only: %i[show edit update destroy]
  before_action :require_customer, except: %i[show index]
  before_action :require_same_customer, only: %i[edit update destroy]

  def show
    
  end

  def index
    @chintus = Chintu.all
  end

  def new
    @chintu = Chintu.new
  end

  def edit
  end

  def create
    @chintu = Chintu.new(chintu_params)
    @chintu.customer = current_customer
    if @chintu.save
      flash[:notice] = 'Article was created successfully.'
      redirect_to @chintu
    else
      render 'new'
    end
  end

  def update
    if @chintu.update(chintu_params)
      flash[:notice] = 'Article was updated successfully.'
      redirect_to @chintu
    else
      render 'edit'
    end
  end

  def destroy
    @chintu.destroy
    redirect_to chintus_path
  end

  private

  def set_chintu
    @chintu = Chintu.find(params[:id])
  end

  def chintu_params
    params.require(:chintu).permit(:title, :description)
  end

  def require_same_customer
    if current_customer != @chintu.customer
      flash[:alert] = 'You can only edit or delete your own article'
      redirect_to @chintu
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
   before_action :set_customer, only: [:show, :edit, :update]
  def show
  @chintus = Chintus.all
  end
  def index
   @customers = Customer.all
  end
  def new
    @customer = Customer.new
  end
  def edit

  end
  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash[:notice] = "Welcome to the Alpha Blog #{@customer.username}, you have successfully signed up"
      redirect_to chintus_path
    else
      render 'new'
    end
  end
  def update
    if @customer.update(customer_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @customer
    else
      render 'edit'
    end
  end
  private
  def customer_params
    params.require(:customer).permit(:username, :email, :password)
  end
  def set_customer
      @customer = Customer.find(params[:id])
  end
end

app/controllers/helpers/about_helper.rb
module AboutHelper
end

app/controllers/helpers/application_helper.rb
module ApplicationHelper
  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
 end

 def logged_in?
   !!current_user
 end
end

app/controllers/helpers/articles_helper.rb
module ArticlesHelper
end

app/controllers/helpers/pages_helper.rb
module PagesHelper
end

app/controllers/helpers/tables_helper.rb
module TablesHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
  def about
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  customer = Customer.find_by(email: params[:session][:email])
      if customer && customer.authenticate(params[:session][:password])
        session[:customer_id] = customer.id
        flash[:notice] = "Logged in successfully"
        redirect_to customer
      else
        flash.now[:alert] = "There was something wrong with your login details"
        render 'new'
      end
  end

  def destroy
    session[:customer_id] = nil
  flash[:notice] = "Logged out"
  redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end
  def current_customer
   @current_customer ||= Customer.find(session[:customer_id]) if session[:customer_id]
 end

 def logged_in?
   !!current_customer
 end
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/chintus/_chintu.html.erb
<div class="container">
<% @chintus.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= article.customer.username if article.customer  %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, chintu_path(article), class: "text-success" %></h5>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
          <%= link_to "View", chintu_path(article), class: "btn btn-outline-success" %>
           <% if logged_in? && article.customer == current_customer %>
          <%= link_to "Edit", edit_chintu_path(article), class: "btn btn-outline-info" %>
          <%= link_to "Delete", chintu_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>

        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(article.created_at) %> ago,
          edited <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>
</div>

app/views/chintus/_form.html.erb
<% if @chintu.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @chintu.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @chintu, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/chintus/edit.html.erb
<h1>Edit chintu</h1>

    <%= render 'form' %>
<%= link_to 'Cancel and return to chintus listing', chintus_path %>

app/views/chintus/index.html.erb
<%= render 'chintu' %> 

app/views/chintus/new.html.erb
  <h1>Create a new article</h1>
  <%= render 'form' %>

<%= link_to 'Return to chintus listing', chintus_path %>

app/views/chintus/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title: </strong><%= @chintu.title %></p>
<p><strong>Description: </strong><%= @chintu.description %></p>

<%= link_to 'Edit', edit_chintu_path(@chintu) %> |
<%= link_to 'Delete', chintu_path(@chintu), method: :delete, data: { confirm: "Are you sure?" } %> |
<%= link_to 'Return to chintus listing', chintus_path %>

app/views/customers/_form.html.erb
<% if @customer.errors.any? %>
  <h2>The following errors prevented customer  from being saved</h2>
  <ul>
    <% @customer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @customer, local: true) do |f| %>

  <p class="text-center mt-4">
    <%= f.label :username %><br/>
    <%= f.text_field :username %>
  </p>

  <p class="text-center mt-4">
    <%= f.label :email %><br/>
    <%= f.email_field :email %>
  </p>

    <p class="text-center mt-4">
      <%= f.label :password %><br/>
      <%= f.password_field :password %>
    </p>


  <p class="text-center mt-4">
    <%= f.submit(@customer.new_record? ? "Sign up" : "Update account") %>
  </p>

<% end %>

app/views/customers/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/customers/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="container">
  <% @customers.each do |customer| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to customer.username, customer %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(customer, size: 150), customer %>
            </h5>
            <p class="card-text"><%= pluralize(customer.chintus.count, "article") %></p>
             <% if logged_in? && customer == current_customer %>
            <%= link_to "View profile", customer, class: "btn btn-outline-success" %>
            <%= link_to "Edit profile", edit_customer_path(customer), class: "btn btn-outline-info" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(customer.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/customers/new.html.erb
<h1 class="text-center mt-4">Sign up</h1>
<%= render 'form' %>

app/views/customers/show.html.erb
<h1 class="text-center mt-4"><%= @customer.username %>'s profile</h1>


<%= gravatar_for @customer, size: 200 %>
  <% if logged_in? && @customer == current_customer %>
<div class="text-center mt-4">
  <%= link_to "Edit your profile", edit_customer_path(@customer), class: "btn btn-outline-info" %>

</div>
 <% end %>
<h3 class="text-center mt-4">Chintus</h3>

<%= render 'chintus/chintu' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
     <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">ALPHA </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link text-success" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-success" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

    <% flash.each do |name, msg| %>
       <%= msg %>
     <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>chintu</h2>
<h3> chintu</h3>
<p><%= link_to 'go back to home page',home_path %></p>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">Alpha </h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p><%= link_to 'chintus link', chintus_path, class:'text-white' %></p>
     <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>